package Presentacion;


import Presentacion.LoginForm;
import Zimagenes.FondoPanel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author DERICK ALEXIS
 */
public class Dashboard extends javax.swing.JFrame {
    
    
    
    private LoginForm v1; // Variable de tipo LogicForm
    RegistrarFrame v3 = new RegistrarFrame();
    PagosFrame v4 = new PagosFrame();
    MedidorFrame v5 = new MedidorFrame();
    DeudoresFrame v6 = new DeudoresFrame();
    HistorialFrame v7 = new HistorialFrame();
   
    public Dashboard() {
    // Usar el FondoPanel 
    FondoPanel fondo = new FondoPanel("D:/ejemploInterfaz/src/main/java/Zimagenes/aguadash.jpg"); 
    setContentPane(fondo);
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();
        btnBotonRegistrarV3 = new javax.swing.JButton();
        btnPagosV4 = new javax.swing.JButton();
        btnMedidoresV5 = new javax.swing.JButton();
        btnDeudoresV6 = new javax.swing.JButton();
        btnHistorialV7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        jLabel1.setText("FactuTrack");

        btnRegresar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnRegresar.setText("Cerrar sesión");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        btnBotonRegistrarV3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnBotonRegistrarV3.setText("Registrar usuario");
        btnBotonRegistrarV3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBotonRegistrarV3ActionPerformed(evt);
            }
        });

        btnPagosV4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnPagosV4.setText("Realizar pagos");
        btnPagosV4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagosV4ActionPerformed(evt);
            }
        });

        btnMedidoresV5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnMedidoresV5.setText("Ingreso de consumo medidores");
        btnMedidoresV5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMedidoresV5ActionPerformed(evt);
            }
        });

        btnDeudoresV6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnDeudoresV6.setText("Visualizar deudores");
        btnDeudoresV6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeudoresV6ActionPerformed(evt);
            }
        });

        btnHistorialV7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnHistorialV7.setText("Historial de consumo de usuario");
        btnHistorialV7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistorialV7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBotonRegistrarV3, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnPagosV4, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnMedidoresV5, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDeudoresV6, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnHistorialV7)
                    .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBotonRegistrarV3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPagosV4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMedidoresV5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeudoresV6, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 326, Short.MAX_VALUE)
                .addComponent(btnHistorialV7, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setV1(LoginForm v1) { // Metodo para setear la ventana V11111
        this.v1 = v1;
    }
    
    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        v1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnRegresarActionPerformed

    
    private void btnBotonRegistrarV3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBotonRegistrarV3ActionPerformed
        // TODO add your handling code here:
        v3.setV2(this); // Nos habre la ventana V3 registrar usuarios
        v3.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnBotonRegistrarV3ActionPerformed

    private void btnPagosV4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagosV4ActionPerformed
        // TODO add your handling code here:
        v4.setV2(this); // Nos habre la ventana V4 o registrar pagos
        v4.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnPagosV4ActionPerformed

    
    private void btnDeudoresV6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeudoresV6ActionPerformed
        // TODO add your handling code here:
        v6.setV2(this); // Nos habre la ventana V6 o registrar pagos
        v6.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnDeudoresV6ActionPerformed

    private void btnMedidoresV5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMedidoresV5ActionPerformed
        // TODO add your handling code here:
        v5.setV2(this); // Nos habre la ventana V7 o registrar pagos
        v5.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnMedidoresV5ActionPerformed

    private void btnHistorialV7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistorialV7ActionPerformed
        // TODO add your handling code here:
        v7.setV2(this); // Nos habre la ventana V7 o registrar pagos
        v7.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnHistorialV7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBotonRegistrarV3;
    private javax.swing.JButton btnDeudoresV6;
    private javax.swing.JButton btnHistorialV7;
    private javax.swing.JButton btnMedidoresV5;
    private javax.swing.JButton btnPagosV4;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
